version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  # This is a test container which tests our application
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm","run","test"]
